CREATE TABLE LIVRO (
     ID integer NOT NULL PRIMARY KEY,
     TITULO VARCHAR(255) NOT NULL,
     AUTOR VARCHAR(255) NOT NULL,
     PAGINAS INTEGER,
     ISBN INTEGER,
     NACIONAL BOOLEAN
);
CREATE TABLE USUARIO (
     USUARIO VARCHAR(255) NOT NULL PRIMARY KEY,
     SENHA VARCHAR(255) NOT NULL
);
